# -*- coding: utf-8 -*-
"""МАМП - 4_Михаляк_С++

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cQAmHcNFeL_u6E4Lkkd6ebEasb8mZGd
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile queue_sim.cpp
# #include <iostream>
# #include <queue>
# #include <cstdlib>
# #include <ctime>
# 
# struct Customer {
#     int id;
#     int serviceTime;
# };
# 
# int main() {
#     std::srand(static_cast<unsigned int>(std::time(nullptr)));
# 
#     std::queue<Customer> q;
#     int currentTime = 0;
#     int totalTime = 100;
#     int nextCustomerId = 1;
#     int customersServed = 0;
#     int totalWaitingTime = 0;
#     int currentServiceRemaining = 0;
# 
#     Customer currentCustomer;
#     bool hasCurrentCustomer = false;
# 
#     while (currentTime < totalTime) {
#         if (std::rand() % 100 < 30) {
#             Customer c;
#             c.id = nextCustomerId++;
#             c.serviceTime = 1 + std::rand() % 5;
#             q.push(c);
#             std::cout << "Час " << currentTime << ": прийшов покупець #" << c.id
#                       << " (час обслуговування " << c.serviceTime << ")\n";
#         }
# 
#         if (!hasCurrentCustomer && !q.empty()) {
#             currentCustomer = q.front();
#             q.pop();
#             currentServiceRemaining = currentCustomer.serviceTime;
#             hasCurrentCustomer = true;
#             std::cout << "Час " << currentTime << ": почали обслуговувати покупця #"
#                       << currentCustomer.id << "\n";
#         }
# 
#         if (hasCurrentCustomer) {
#             currentServiceRemaining--;
#             if (currentServiceRemaining <= 0) {
#                 hasCurrentCustomer = false;
#                 customersServed++;
#                 std::cout << "Час " << currentTime << ": завершили обслуговування покупця #"
#                           << currentCustomer.id << "\n";
#             }
#         }
# 
#         totalWaitingTime += static_cast<int>(q.size());
#         currentTime++;
#     }
# 
#     std::cout << "\n=== Підсумки моделювання ===\n";
#     std::cout << "Всього обслуговано покупців: " << customersServed << "\n";
#     std::cout << "Середній час очікування (приблизно): ";
#     if (customersServed > 0)
#         std::cout << static_cast<double>(totalWaitingTime) / customersServed << "\n";
#     else
#         std::cout << "0\n";
#     std::cout << "Людей у черзі наприкінці: " << q.size() << "\n";
# 
#     return 0;
# }
#

!g++ queue_sim.cpp -o queue_sim

!./queue_sim