# -*- coding: utf-8 -*-
"""МАМП - 3_Михаляк_Java

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YiIRh6lEyJ_kZUCpx5wGVxzEI9DkKpPY
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Main.java
# import java.util.ArrayList;
# import java.util.List;
# import java.util.Scanner;
# 
# class Student {
#     private String name;
#     private int age;
#     private String group;
# 
#     public Student(String name, int age, String group) {
#         this.name = name;
#         this.age = age;
#         this.group = group;
#     }
# 
#     public String getName() { return name; }
#     public int getAge() { return age; }
#     public String getGroup() { return group; }
# 
#     @Override
#     public String toString() {
#         return "Ім'я: " + name + ", Вік: " + age + ", Група: " + group;
#     }
# }
# 
# public class Main {
#     private static final Scanner scanner = new Scanner(System.in);
#     private static final List<Student> students = new ArrayList<>();
# 
#     public static void main(String[] args) {
#         int choice;
#         do {
#             printMenu();
#             choice = readInt("Ваш вибір: ");
#             switch (choice) {
#                 case 1 -> addStudent();
#                 case 2 -> showStudents();
#                 case 3 -> searchByGroup();
#                 case 4 -> System.out.println("Вихід...");
#                 default -> System.out.println("Невірний вибір.");
#             }
#         } while (choice != 4);
#     }
# 
#     private static void printMenu() {
#         System.out.println("\n=== Система реєстрації студентів ===");
#         System.out.println("1. Додати студента");
#         System.out.println("2. Показати всіх студентів");
#         System.out.println("3. Пошук за групою");
#         System.out.println("4. Вихід");
#     }
# 
#     private static void addStudent() {
#         System.out.print("Введіть ім'я: ");
#         String name = scanner.nextLine();
#         int age = readInt("Введіть вік: ");
#         System.out.print("Введіть групу: ");
#         String group = scanner.nextLine();
# 
#         students.add(new Student(name, age, group));
#         System.out.println("Студента додано!");
#     }
# 
#     private static void showStudents() {
#         if (students.isEmpty()) {
#             System.out.println("Список порожній.");
#             return;
#         }
#         System.out.println("\n=== Список студентів ===");
#         for (Student s : students) {
#             System.out.println(s);
#         }
#     }
# 
#     private static void searchByGroup() {
#         System.out.print("Введіть групу для пошуку: ");
#         String group = scanner.nextLine();
#         System.out.println("\nРезультати пошуку:");
#         boolean found = false;
#         for (Student s : students) {
#             if (s.getGroup().equalsIgnoreCase(group)) {
#                 System.out.println(s);
#                 found = true;
#             }
#         }
#         if (!found) {
#             System.out.println("Студентів з такою групою не знайдено.");
#         }
#     }
# 
#     private static int readInt(String message) {
#         while (true) {
#             try {
#                 System.out.print(message);
#                 String line = scanner.nextLine();
#                 return Integer.parseInt(line.trim());
#             } catch (NumberFormatException ex) {
#                 System.out.println("Введіть коректне число.");
#             }
#         }
#     }
# }
#

!javac Main.java

!java Main