# -*- coding: utf-8 -*-
"""МАМП - 5_Михаляк_С#

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wgp5t1MSVybr40xHQaSUZE3NqFcj8AYt
"""

!apt-get update
!apt-get install -y mono-complete

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Program.cs
# using System;
# using System.IO;
# using System.Text;
# 
# class Program
# {
#     const string FileName = "notes.txt";
#     const int Shift = 3;
# 
#     static void Main()
#     {
#         int choice;
#         do
#         {
#             PrintMenu();
#             Console.Write("Ваш вибір: ");
#             if (!int.TryParse(Console.ReadLine(), out choice))
#             {
#                 Console.WriteLine("Некоректне введення.");
#                 continue;
#             }
# 
#             switch (choice)
#             {
#                 case 1:
#                     CreateNote();
#                     break;
#                 case 2:
#                     ShowNotes();
#                     break;
#                 case 3:
#                     Console.WriteLine("Вихід...");
#                     break;
#                 default:
#                     Console.WriteLine("Невірний вибір.");
#                     break;
#             }
#         } while (choice != 3);
#     }
# 
#     static void PrintMenu()
#     {
#         Console.WriteLine("\n=== Нотатки з шифруванням ===");
#         Console.WriteLine("1. Створити нотатку");
#         Console.WriteLine("2. Показати всі нотатки");
#         Console.WriteLine("3. Вихід");
#     }
# 
#     static void CreateNote()
#     {
#         Console.Write("Введіть текст нотатки: ");
#         string text = Console.ReadLine() ?? "";
#         string encrypted = Encrypt(text);
# 
#         File.AppendAllText(FileName, encrypted + Environment.NewLine, Encoding.UTF8);
#         Console.WriteLine("Нотатку збережено (в зашифрованому вигляді).");
#     }
# 
#     static void ShowNotes()
#     {
#         if (!File.Exists(FileName))
#         {
#             Console.WriteLine("Файл нотаток відсутній.");
#             return;
#         }
# 
#         string[] lines = File.ReadAllLines(FileName, Encoding.UTF8);
#         Console.WriteLine("\n=== Збережені нотатки (розшифровані) ===");
#         foreach (var encrypted in lines)
#         {
#             string decrypted = Decrypt(encrypted);
#             Console.WriteLine("- " + decrypted);
#         }
#     }
# 
#     static string Encrypt(string input)
#     {
#         var sb = new StringBuilder();
#         foreach (char c in input)
#         {
#             sb.Append((char)(c + Shift));
#         }
#         return sb.ToString();
#     }
# 
#     static string Decrypt(string input)
#     {
#         var sb = new StringBuilder();
#         foreach (char c in input)
#         {
#             sb.Append((char)(c - Shift));
#         }
#         return sb.ToString();
#     }
# }
#

!mcs Program.cs

!mono Program.exe