# -*- coding: utf-8 -*-
"""МАМП - 2_Михаляк_JavaScript

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRHqPzbnOU8l1Q4UHnfJJvgiES5I20zn
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile index.html
# <!DOCTYPE html>
# <html lang="uk">
# <head>
#   <meta charset="UTF-8">
#   <title>Clicker Game</title>
#   <style>
#     body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
#     #score { font-size: 32px; margin: 20px; }
#     #bonus { margin-top: 20px; font-weight: bold; }
#     button { padding: 10px 20px; font-size: 18px; }
#   </style>
# </head>
# <body>
#   <h1>Clicker Game</h1>
#   <div id="score">Рахунок: 0</div>
#   <button id="clickBtn">Клацни мене!</button>
# 
#   <div id="bonus"></div>
# 
#   <script>
#     let score = 0;
#     let bonusActive = false;
#     let bonusMultiplier = 2;
#     let bonusTimer = null;
# 
#     const scoreEl = document.getElementById("score");
#     const clickBtn = document.getElementById("clickBtn");
#     const bonusEl = document.getElementById("bonus");
# 
#     function updateScore() {
#       scoreEl.textContent = "Рахунок: " + score;
#     }
# 
#     function activateBonus() {
#       if (bonusActive) return;
#       bonusActive = true;
#       bonusEl.textContent = "БОНУС! Усі кліки x" + bonusMultiplier + " (10 секунд)";
#       bonusTimer = setTimeout(() => {
#         bonusActive = false;
#         bonusEl.textContent = "";
#       }, 10000);
#     }
# 
#     setInterval(activateBonus, 15000);
# 
#     clickBtn.addEventListener("click", () => {
#       if (bonusActive) {
#         score += bonusMultiplier;
#       } else {
#         score += 1;
#       }
#       updateScore();
#     });
# 
#     updateScore();
#   </script>
# </body>
# </html>
#

from google.colab import files
files.download("index.html")