# -*- coding: utf-8 -*-
"""МАМП - 6_Михаляк_PHP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eF1eAANAsWsCsL1wX8cLZICjpSTv6OiP
"""

!apt-get update
!apt-get install -y php

# Commented out IPython magic to ensure Python compatibility.
# %%writefile index.php
# <?php
# $filename = "posts.txt";
# 
# function load_posts($filename) {
#     if (!file_exists($filename)) {
#         return [];
#     }
#     $lines = file($filename, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
#     $posts = [];
#     foreach ($lines as $line) {
#         $parts = explode("|", $line, 2);
#         if (count($parts) == 2) {
#             $posts[] = ["date" => $parts[0], "text" => $parts[1]];
#         }
#     }
#     return $posts;
# }
# 
# function save_post($filename, $text) {
#     $date = date("Y-m-d H:i:s");
#     $line = $date . "|" . str_replace("\n", " ", $text) . PHP_EOL;
#     file_put_contents($filename, $line, FILE_APPEND | LOCK_EX);
# }
# 
# if ($_SERVER["REQUEST_METHOD"] === "POST") {
#     $text = trim($_POST["text"] ?? "");
#     if ($text !== "") {
#         save_post($filename, $text);
#     }
#     header("Location: " . $_SERVER["PHP_SELF"]);
#     exit;
# }
# 
# $posts = load_posts($filename);
# ?>
# <!DOCTYPE html>
# <html lang="uk">
# <head>
#     <meta charset="UTF-8">
#     <title>Міні-блог</title>
#     <style>
#         body { font-family: Arial, sans-serif; max-width: 800px; margin: 20px auto; }
#         .post { border-bottom: 1px solid #ccc; padding: 10px 0; }
#         .date { font-size: 12px; color: #666; }
#         textarea { width: 100%; height: 80px; }
#         button { padding: 5px 10px; margin-top: 5px; }
#     </style>
# </head>
# <body>
# 
# <h1>Міні-блог</h1>
# 
# <form method="post">
#     <textarea name="text" required placeholder="Введіть текст..."></textarea><br>
#     <button type="submit">Опублікувати</button>
# </form>
# 
# <h2>Записи:</h2>
# <?php if (empty($posts)): ?>
#     <p>Ще н
#

!php -S 0.0.0.0:8000 -t .