# -*- coding: utf-8 -*-
"""МАМП - 7_Михаляк_GO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yw5WKdWHgKq0pL5uZiHSoNNnPckstMwm
"""

!apt-get update
!apt-get install -y golang-go netcat

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.go
# package main
# 
# import (
# 	"bufio"
# 	"fmt"
# 	"net"
# )
# 
# var (
# 	clients = make(map[net.Conn]bool)
# 	addCh   = make(chan net.Conn)
# 	rmCh    = make(chan net.Conn)
# 	msgCh   = make(chan string)
# )
# 
# func handleConnection(conn net.Conn) {
# 	defer conn.Close()
# 	addCh <- conn
# 
# 	name := conn.RemoteAddr().String()
# 	welcome := fmt.Sprintf("Користувач %s приєднався до чату\n", name)
# 	msgCh <- welcome
# 
# 	reader := bufio.NewScanner(conn)
# 	for reader.Scan() {
# 		text := reader.Text()
# 		if text == "/quit" {
# 			break
# 		}
# 		msg := fmt.Sprintf("%s: %s\n", name, text)
# 		msgCh <- msg
# 	}
# 	rmCh <- conn
# 	msgCh <- fmt.Sprintf("Користувач %s вийшов з чату\n", name)
# }
# 
# func broadcaster() {
# 	for {
# 		select {
# 		case conn := <-addCh:
# 			clients[conn] = true
# 		case conn := <-rmCh:
# 			delete(clients, conn)
# 		case msg := <-msgCh:
# 			for c := range clients {
# 				fmt.Fprint(c, msg)
# 			}
# 			fmt.Print(msg) // дублюємо на сервер
# 		}
# 	}
# }
# 
# func main() {
# 	go broadcaster()
# 
# 	ln, err := net.Listen("tcp", ":9000")
# 	if err != nil {
# 		fmt.Println("Помилка запуску сервера:", err)
# 		return
# 	}
# 	fmt.Println("Сервер чату запущено на порту 9000")
# 
# 	for {
# 		conn, err := ln.Accept()
# 		if err != nil {
# 			fmt.Println("Помилка підключення:", err)
# 			continue
# 		}
# 		go handleConnection(conn)
# 	}
# }
#

!nc 127.0.0.1 9000